create table
  public.account (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    username character varying not null,
    password character varying not null,
    profile_picture text null,
    constraint account_pkey primary key (id),
    constraint account_username_key unique (username)
  ) tablespace pg_default;

create table
  public.household (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    code character varying null,
    color bigint not null default '0'::bigint,
    constraint Household_pkey primary key (id),
    constraint Household_code_key unique (code),
    constraint Household_name_key unique (name),
    constraint household_color_check check ((color <= 360)),
    constraint household_name_check check ((length((name)::text) < 26))
  ) tablespace pg_default;

create table
  public.account_to_household (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    household_id bigint not null,
    permission character varying not null default 'member'::character varying,
    account_id uuid null,
    constraint UserToHousehold_pkey primary key (id),
    constraint account_to_household_account_id_fkey foreign key (account_id) references account (id) on update cascade on delete cascade,
    constraint account_to_household_household_id_fkey foreign key (household_id) references household (id) on update cascade on delete cascade,
    constraint user_to_household_household_id_fkey foreign key (household_id) references household (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    quantity text not null,
    household_id bigint not null,
    bought boolean not null default false,
    image text null,
    constraint Items_pkey primary key (id),
    constraint Items_household_id_fkey foreign key (household_id) references household (id) on update cascade on delete cascade,
    constraint Items_household_id_fkey1 foreign key (household_id) references household (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.session (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    expire_date timestamp with time zone null,
    ip_address character varying null,
    account_id uuid null default gen_random_uuid (),
    constraint session_pkey primary key (id),
    constraint session_account_id_fkey foreign key (account_id) references account (id) on update cascade on delete cascade
  ) tablespace pg_default;
